import { randomUUID } from 'crypto'; import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common'; import { InjectRepository } from '@nestjs/typeorm'; import { Repository } from 'typeorm';
import { BoardEntity, CardLayoutFieldEntity, KanbanLayoutColumnEntity, ProjectInstanceEntity, ProjectItemEntity } from '../../database/entities'; import { ProjectAccessService } from '../../common/project-access.service'; import { AuditService } from '../audit/audit.service'; import { CreateItemDto, UpdateItemDto } from './items.dto';
@Injectable() export class ItemsService{constructor(@InjectRepository(ProjectItemEntity)private items:Repository<ProjectItemEntity>,@InjectRepository(BoardEntity)private boards:Repository<BoardEntity>,@InjectRepository(ProjectInstanceEntity)private instances:Repository<ProjectInstanceEntity>,@InjectRepository(KanbanLayoutColumnEntity)private columns:Repository<KanbanLayoutColumnEntity>,@InjectRepository(CardLayoutFieldEntity)private fields:Repository<CardLayoutFieldEntity>,private access:ProjectAccessService,private audit:AuditService){}
 private snapshot(i:ProjectItemEntity){return {projectId:i.projectId,id:i.id,boardId:i.boardId,parentItemId:i.parentItemId,instanceLevel:i.instanceLevel,columnId:i.columnId,cardLayoutId:i.cardLayoutId,position:i.position,data:i.data,deletedAt:i.deletedAt?.toISOString()??null}}
 private async validateData(layoutId:string,data:Record<string,unknown>){
  const fields=await this.fields.find({where:{cardLayoutId:layoutId}});
  for(const f of fields){
    const value=data[f.fieldKey];
    if(f.required && (value===undefined || value===null || value===''))throw new BadRequestException(`Campo obrigatório ausente: ${f.label}`);
    if(value===undefined || value===null)continue;
    const stringTypes=['text','textarea','date','datetime','select','user','image','file','url','color'];
    if(stringTypes.includes(f.fieldType) && typeof value!=='string')throw new BadRequestException(`${f.label} deve ser texto.`);
    if(['number','decimal'].includes(f.fieldType) && typeof value!=='number')throw new BadRequestException(`${f.label} deve ser número.`);
    if(f.fieldType==='boolean' && typeof value!=='boolean')throw new BadRequestException(`${f.label} deve ser verdadeiro/falso.`);
    if(['multiselect','tags','repeater'].includes(f.fieldType) && !Array.isArray(value))throw new BadRequestException(`${f.label} deve ser uma lista.`);
  }
  return true;
 }
 async create(projectId:string,uid:string,d:CreateItemDto){await this.access.assertMember(projectId,uid,true);const b=await this.boards.findOne({where:{id:d.boardId,projectId}});if(!b)throw new NotFoundException('Board não encontrado.');const instance=await this.instances.findOneByOrFail({id:b.projectInstanceId});const column=d.columnId?await this.columns.findOne({where:{id:d.columnId,kanbanLayoutId:b.kanbanLayoutId}}):await this.columns.findOne({where:{kanbanLayoutId:b.kanbanLayoutId,isInitial:true}});if(!column)throw new BadRequestException('Coluna inicial não configurada.');const layout=d.cardLayoutId??b.cardLayoutId;await this.validateData(layout,d.data);const item=this.items.create({projectId,id:randomUUID(),boardId:b.id,parentItemId:b.parentItemId,instanceLevel:instance.instanceLevel,columnId:column.id,cardLayoutId:layout,position:d.position??Date.now(),data:d.data,createdBy:uid});const saved=await this.items.save(item);await this.audit.log({projectId,userId:uid,entityType:'ITEM',entityId:saved.id,actionType:'CREATE',after:this.snapshot(saved)});return saved;}
 async get(projectId:string,id:string,uid:string){await this.access.assertMember(projectId,uid);const i=await this.items.findOne({where:{projectId,id}});if(!i)throw new NotFoundException();return i;}
 async update(projectId:string,id:string,uid:string,d:UpdateItemDto){await this.access.assertMember(projectId,uid,true);const i=await this.items.findOne({where:{projectId,id}});if(!i)throw new NotFoundException();const before=this.snapshot(i);if(d.columnId){const b=await this.boards.findOneByOrFail({id:i.boardId});if(!(await this.columns.findOne({where:{id:d.columnId,kanbanLayoutId:b.kanbanLayoutId}})))throw new BadRequestException('Coluna não pertence ao Kanban deste board.');i.columnId=d.columnId;}if(d.cardLayoutId)i.cardLayoutId=d.cardLayoutId;if(d.position!==undefined)i.position=d.position;if(d.data!==undefined){await this.validateData(i.cardLayoutId,d.data);i.data=d.data;}const saved=await this.items.save(i);const actionType=d.columnId&&d.columnId!==before.columnId?'MOVE':(d.position!==undefined&&d.position!==before.position?'REORDER':'UPDATE');await this.audit.log({projectId,userId:uid,entityType:'ITEM',entityId:id,actionType,before,after:this.snapshot(saved)});return saved;}
 async remove(projectId:string,id:string,uid:string){await this.access.assertMember(projectId,uid,true);const i=await this.items.findOne({where:{projectId,id}});if(!i)throw new NotFoundException();const before=this.snapshot(i);await this.items.softRemove(i);await this.audit.log({projectId,userId:uid,entityType:'ITEM',entityId:id,actionType:'DELETE',before,after:{...before,deletedAt:new Date().toISOString()}});return {ok:true};}
 async restore(projectId:string,id:string,uid:string){await this.access.assertMember(projectId,uid,true);const i=await this.items.findOne({where:{projectId,id},withDeleted:true});if(!i)throw new NotFoundException();const before=this.snapshot(i);i.deletedAt=null;const saved=await this.items.save(i);await this.audit.log({projectId,userId:uid,entityType:'ITEM',entityId:id,actionType:'RESTORE',before,after:this.snapshot(saved)});return saved;}
 async restoreAction(projectId:string,id:string,actionId:string,uid:string){await this.access.assertMember(projectId,uid,true);const a=await this.audit.find(actionId);if(!a||a.projectId!==projectId||a.entityType!=='ITEM'||a.entityId!==id||!a.beforeData)throw new BadRequestException('Ação não pode ser restaurada.');const i=await this.items.findOne({where:{projectId,id},withDeleted:true});if(!i)throw new NotFoundException();const before=this.snapshot(i);const s=a.beforeData as any;if(s.columnId)i.columnId=s.columnId;if(s.cardLayoutId)i.cardLayoutId=s.cardLayoutId;if(s.position!==undefined)i.position=Number(s.position);if(s.data)i.data=s.data;i.deletedAt=s.deletedAt?new Date(s.deletedAt):null;const saved=await this.items.save(i);await this.audit.log({projectId,userId:uid,entityType:'ITEM',entityId:id,actionType:'RESTORE_VERSION',before,after:this.snapshot(saved),metadata:{restoredFromActionId:actionId}});return saved;}
}
